### ISSUE TITLE
mysql version

### ISSUE THREAD

**Issue by blondie63** [mubaidr/node-vue-template#1]
I'm converting this project to use mysql
I've add port in option.js and modified the new sequelize cmds
How to avoid use of SET QUOTED_IDENTIFIER ?

**Comment by mubaidr** [comment]
Welcome! 

I have not used mysql much, but will definitely look if its possible to help.

**Comment by mubaidr** [comment]
According to mySQL documentation, you can escape a quote using an additional one. 

> A “'” inside a string quoted with “'” may be written as “''”.

**Comment by soroka41** [comment]
I'm converting this project to use mysql. There were difficulties with adapting the query under mysql SET QUOTED_IDENTIFIER ?

**Comment by mubaidr** [comment]
I have plans to improve this template. Will be able to update in the coming week. This issue will be tackled too.

**Comment by mubaidr** [comment]
I believe this should be fixed with: https://github.com/mubaidr/node-vue-template/commit/3fa623965a28ded6419514c76edb47ad912579d8
